import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { CacheSchemaDescriptor } from '../schema';

export function renderCacheSchemaModule(descriptor: CacheSchemaDescriptor): string {
    return [
        '/* Generated by prisma-cache-tags-generator. Do not edit. */',
        "import type { CacheSchemaDescriptor } from 'prisma-extension-cache-tags';",
        '',
        `export const cacheSchema = ${JSON.stringify(descriptor, null, 4)} as const satisfies CacheSchemaDescriptor;`,
        '',
    ].join('\n');
}

export async function writeGeneratedCacheSchema(output: string, descriptor: CacheSchemaDescriptor): Promise<void> {
    await mkdir(output, { recursive: true });
    await writeFile(join(output, 'index.ts'), renderCacheSchemaModule(descriptor), 'utf8');
}
